### ISSUE TITLE
发现一个错误，请教一下

### ISSUE THREAD

**Issue by PiPiCaptain** [Ryan-Shz/FastWebView#6]
020-06-11 17:49:05.700 5293-5913 W/System.err: java.lang.IllegalArgumentException: reasonPhrase can't be empty.
2020-06-11 17:49:05.700 5293-5913 W/System.err:     at android.webkit.WebResourceResponse.setStatusCodeAndReasonPhrase(WebResourceResponse.java:138)
2020-06-11 17:49:05.700 5293-5913 W/System.err:     at android.webkit.WebResourceResponse.<init>(WebResourceResponse.java:76)
2020-06-11 17:49:05.701 5293-5913 W/System.err:     at com.ryan.github.view.offline.DefaultWebResponseGenerator.generate(DefaultWebResponseGenerator.java:71)
2020-06-11 17:49:05.701 5293-5913 W/System.err:     at com.ryan.github.view.offline.OfflineServerImpl.get(OfflineServerImpl.java:66)
2020-06-11 17:49:05.701 5293-5913 W/System.err:     at com.ryan.github.view.WebViewCacheImpl.getResource(WebViewCacheImpl.java:50)
2020-06-11 17:49:05.701 5293-5913 W/System.err:     at com.ryan.github.view.InnerFastClient.loadFromWebViewCache(InnerFastClient.java:274)
2020-06-11 17:49:05.701 5293-5913 W/System.err:     at com.ryan.github.view.InnerFastClient.onIntercept(InnerFastClient.java:264)
2020-06-11 17:49:05.701 5293-5913 W/System.err:     at com.ryan.github.view.InnerFastClient.shouldInterceptRequest(InnerFastClient.java:245)
2020-06-11 17:49:05.701 5293-5913 W/System.err:     at com.android.webview.chromium.WebViewContentsClientAdapter.shouldInterceptRequest(WebViewContentsClientAdapter.java:52)
2020-06-11 17:49:05.701 5293-5913 W/System.err:     at org.chromium.android_webview.AwContents$BackgroundThreadClientImpl.shouldInterceptRequest(AwContents.java:9)
2020-06-11 17:49:05.701 5293-5913 W/System.err:     at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(AwContentsBackgroundThreadClient.java:11)

**Comment by PiPiCaptain** [comment]
场景是这样的：APP加载我们自己的H5，但H5里面又调用了别人的H5，二个都是https

**Comment by PiPiCaptain** [comment]
这个错误会导致闪退，而且100%复现

**Comment by Ryan-Shz** [comment]
我举个例子，假如我们请求了一个远程资源，这个资源的HTTP响应头如下：
```
HTTP/1.1 200 OK
X-Powered-By: Express
Accept-Ranges: bytes
Cache-Control: public, max-age=0
Last-Modified: Thu, 11 Jun 2020 13:48:21 GMT
ETag: W/"b82e7-172a3a381dd"
Content-Type: application/javascript; charset=UTF-8
Vary: Accept-Encoding
Content-Encoding: gzip
Date: Thu, 11 Jun 2020 13:52:18 GMT
Transfer-Encoding: chunked
Connection: keep-alive
```
其中第一行是 **HTTP/1.1 200 OK**
这个OK其实就是reasonPhrase，正常来讲每个HTTP返回码都会有对应的reasonPhrase，你这个异常是由于没有返回reasonPhrase，可能的场景是你们的H5中请求了某些服务接口，这些接口未正确返回reasonPhrase。

这种场景我近期做一下兼容。

**Comment by PiPiCaptain** [comment]
@Ryan-Shz 好的，感谢

**Comment by Ryan-Shz** [comment]
代码已提交，在这里[commit](https://github.com/Ryan-Shz/FastWebView/commit/395f4bd726d5e0c4096b527d39cea9b94630b56c)
版本更新为1.0.8，你可以再试一下[握手]

@PiPiCaptain
