### ISSUE TITLE
又有一个奇怪的问题，请教一下

### ISSUE THREAD

**Issue by PiPiCaptain** [Ryan-Shz/FastWebView#7]
2020-06-14 22:43:35.560 25797-26208/ W/System.err: java.lang.IllegalArgumentException: statusCode can't be in the [300, 399] range.
2020-06-14 22:43:35.561 25797-26208/ W/System.err:     at android.webkit.WebResourceResponse.setStatusCodeAndReasonPhrase(WebResourceResponse.java:135)
2020-06-14 22:43:35.561 25797-26208/ W/System.err:     at android.webkit.WebResourceResponse.<init>(WebResourceResponse.java:77)
2020-06-14 22:43:35.561 25797-26208/ W/System.err:     at com.ryan.github.view.offline.DefaultWebResponseGenerator.generate(DefaultWebResponseGenerator.java:71)
2020-06-14 22:43:35.561 25797-26208/ W/System.err:     at com.ryan.github.view.offline.OfflineServerImpl.get(OfflineServerImpl.java:66)
2020-06-14 22:43:35.561 25797-26208/ W/System.err:     at com.ryan.github.view.WebViewCacheImpl.getResource(WebViewCacheImpl.java:50)
2020-06-14 22:43:35.562 25797-26208/ W/System.err:     at com.ryan.github.view.InnerFastClient.loadFromWebViewCache(InnerFastClient.java:274)
2020-06-14 22:43:35.562 25797-26208/ W/System.err:     at com.ryan.github.view.InnerFastClient.onIntercept(InnerFastClient.java:264)
2020-06-14 22:43:35.562 25797-26208/ W/System.err:     at com.ryan.github.view.InnerFastClient.shouldInterceptRequest(InnerFastClient.java:245)
2020-06-14 22:43:35.562 25797-26208/ W/System.err:     at com.android.webview.chromium.WebViewContentsClientAdapter.shouldInterceptRequest(WebViewContentsClientAdapter.java:79)
2020-06-14 22:43:35.562 25797-26208/ W/System.err:     at org.chromium.android_webview.AwContents$BackgroundThreadClientImpl.shouldInterceptRequest(AwContents.java:9)
2020-06-14 22:43:35.563 25797-26208/ W/System.err:     at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(AwContentsBackgroundThreadClient.java:11)

**Comment by PiPiCaptain** [comment]
![image](https://user-images.githubusercontent.com/22672329/84596981-610eb200-ae93-11ea-9fc4-f617734cea1c.png)

**Comment by PiPiCaptain** [comment]
网页里确实有二个返回了302，咱们这个类库能兼容吗？现在报错，会闪退

**Comment by Ryan-Shz** [comment]
> 网页里确实有二个返回了302，咱们这个类库能兼容吗？现在报错，会闪退

你用最新的包试一下，1.0.9版本

**Comment by Ryan-Shz** [comment]
https://github.com/Ryan-Shz/FastWebView/commit/03b8565287c5cd34e81a54b24e5f0e1ddbfd2068 看这个commit

**Comment by PiPiCaptain** [comment]
@Ryan-Shz 好的，谢谢
